### ISSUE TITLE
Not blocking ads anymore

### ISSUE THREAD

**Issue by bcutter** [WreckingBANG/Joyn-PiHole#1]
Joyn / Pro7 seems to have changed something.

Joyn is still working, but now ads are shown before and during playing videos.

I never saw ads before. This changed few weeks (maybe two) ago.

Did they maybe switch and ship their ads by using their own (or whitelisted) domains now?

**Comment by Master-Rudi** [comment]
Same here, any solutions? Thanks a lot!

**Comment by WreckingBANG** [comment]
I thought nobody would use this lol. I will look into it.

**Comment by bcutter** [comment]
I suspect `hybrid-prd.ad-prd.s.joyn.de`. Added to blocklist, testing it for a while.

**Comment by gonzalesdlx** [comment]
I think for me blacklisting 
joyn-vod-prd.akamaized.net
did do the trick.

**Comment by WreckingBANG** [comment]
I tested it with joyn-vod-prd.akamaized.net and it seemes to work. Added it

**Comment by WreckingBANG** [comment]
added

**Comment by WreckingBANG** [comment]
> I think for me blacklisting 
> joyn-vod-prd.akamaized.net
> did do the trick. 

Thank you

**Comment by bcutter** [comment]
Interesting. For me while I don't see ads anymore:
- `joyn-vod-prd.akamaized.net` is still allowed ✔ (not on the whitelist but also not on the blocklist)
- while `hybrid-prd.ad-prd.s.joyn.de` is not (as it is on the blocklist) ❌
- And I don't even see `joyn-vod-prd.akamaized.net` in the query log.

Maybe we should set both on the blocklist just to be sure?

**Comment by WreckingBANG** [comment]
Hmm that seems weird. I will check tomorrow.

**Comment by PsymonK** [comment]
> Interesting. For me while I don't see ads anymore:
> 
> * `joyn-vod-prd.akamaized.net` is still allowed ✔ (not on the whitelist but also not on the blocklist)
> * while `hybrid-prd.ad-prd.s.joyn.de` is not (as it is on the blocklist) ❌
> * And I don't even see `joyn-vod-prd.akamaized.net` in the query log.
> 
> Maybe we should set both on the blocklist just to be sure?

Same for me! Really weird.

**Comment by WreckingBANG** [comment]
I will set joyn-vod-prd.akamaized.net on the blocklist and close the ticket.

**Comment by PsymonK** [comment]
Sorry to bother you, but that's not working for me.
The problem is, blocking `hybrid-prd.ad-prd.s.joyn.de` works, but in some series or shows like Flash or TV Total the bottom menu won't fade out and after the first time where ads should be shown the stream pauses every 5 minutes and I have to click play every time.
Perhaps I should mention I'm streaming joyn with a fire tv stick.

**Comment by bcutter** [comment]
I can confirm this behavior with slight little differences:

- on an Android device in Firefox browser with user agent set to a Windows device (only option to access Joyn outside the official app when avoiding Google Play Store), the control icons at the bottom will stay visible. After stopping and restarting a video for like 5 times, it finally hides itself. Short breaks every few minutes (5?) where picture/playback just freezes for like 2 to 5 seconds and then continues to play.

- At the same time in all official Joyn apps (only tested iOS and on a Samsung TV with TizenOS) everything is working just perfect. No visual side effects or short playback interruptions, just straight video playback completely without ads.

So I guess those are some side effects of the blocking. Anyway, it's another issue and nothing which seems to be fixable here on the Pi-Hole side.
If I can choose between those side effects and the annoyingly amount of ads, for now I take the first pill.
